import { LoanApplication } from '@/lib/types'

/** Presets tuned for a “first-time / campus-adjacent borrower” narrative (same model, clearer story). */
export const SCENARIOS: { label: string; description: string; data: LoanApplication }[] = [
  {
    label: 'First-time borrower (student-ish)',
    description: 'Part-time income, short history, small education-purpose loan',
    data: {
      age: 21,
      income: 18500,
      employment_years: 1,
      education: 'incomplete_higher',
      loan_amount: 3200,
      loan_term: 24,
      loan_purpose: 'education',
      credit_history_years: 1,
      existing_loans: 0,
      previous_defaults: 0,
      credit_utilization: 0.35,
      debt_to_income: 0.22,
    },
  },
  {
    label: 'Strong applicant',
    description: 'Stable income, long credit history, low utilization',
    data: {
      age: 42,
      income: 95000,
      employment_years: 12,
      education: 'higher',
      loan_amount: 15000,
      loan_term: 36,
      loan_purpose: 'home',
      credit_history_years: 18,
      existing_loans: 1,
      previous_defaults: 0,
      credit_utilization: 0.15,
      debt_to_income: 0.12,
    },
  },
  {
    label: 'High risk applicant',
    description: 'Prior defaults, high utilization, elevated debt load',
    data: {
      age: 27,
      income: 24000,
      employment_years: 1,
      education: 'secondary',
      loan_amount: 18000,
      loan_term: 60,
      loan_purpose: 'consumer',
      credit_history_years: 2,
      existing_loans: 3,
      previous_defaults: 2,
      credit_utilization: 0.88,
      debt_to_income: 0.61,
    },
  },
  {
    label: 'Borderline review',
    description: 'Mixed income, loan size, and credit history signals',
    data: {
      age: 34,
      income: 48000,
      employment_years: 4,
      education: 'higher',
      loan_amount: 22000,
      loan_term: 48,
      loan_purpose: 'auto',
      credit_history_years: 7,
      existing_loans: 2,
      previous_defaults: 1,
      credit_utilization: 0.52,
      debt_to_income: 0.38,
    },
  },
]
